name: ecassion
description: Cross platform Event Management App

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_svg:
  freezed_annotation:
  cached_network_image:
  faker:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  build_runner:
  freezed:
  flutter_launcher_icons:

flutter:
  uses-material-design: false

  assets:
    - images/

flutter_icons:
  ios: true
  android: true
  image_path: "images/splash_logo.png"